### ISSUE TITLE
Interested in using

### ISSUE THREAD

**Issue by ianjohnsa** [Sam-GG/Divinity-Original-Sin-2-Save-Sync#1]
My friend and I recently got the game and were disappointed to see there is no way to easily sync our co-op game so that we can play offline on one of our saves. If your script would help with this I'd be interested in a brief description of how to install/use it. Thanks!

Sorry for posting as issue. Apparently there's no way to DM on Github (I'm somewhat of a GitHub noob and not a programmer myself).

**Comment by Sam-GG** [comment]
No worries! currently, it requires you to sign up for the google cloud platform and set up a project, generate credentials etc. More or less a lot of work for very little. If I get time over the next couple of days I'll see if I can make the project public and clean up the code a little (was planning to anyway). That should hopefully resolve some of the complexity and allow me to provide clear instructions.

**Comment by Sam-GG** [comment]
Hey, sorry for going quiet. I ended up pretty busy with job interviews and studying, and also came to the conclusion that I can't make the google cloud platform project public- which makes setup extremely tedious. Nonetheless, I've posted instructions should anyone want to go for it, and also to help me remember myself when I inevitably forget years from now.
